### ISSUE TITLE
Need help upgrading to 1.2

### ISSUE THREAD

**Issue by BlinkyStitt** [space-physics/igrf#1]
Hello, I just found this library through ardupilot. It looks like the API changes for 1.2 broke their code. I've opened an issue with them (https://github.com/ArduPilot/ardupilot/issues/8451), but am wondering if you have steps for migrating from older versions.

`gridigrf12` changed and now the code is giving `AttributeError: 'int' object has no attribute 'ravel'`.

**Comment by scivision** [comment]
I did an ArduPilot [pull request](https://github.com/ArduPilot/ardupilot/pull/8467) to fix this issue. I think you can just copy the `generate.py` into your directory to make it work.

**Comment by BlinkyStitt** [comment]
Thank you!

**Comment by scivision** [comment]
Note: In v1.3.1 (released just now) I include the inclination and declination computations as part of the normal output. I did a new pull request for Ardupilot, further simplifying their code.
