### ISSUE TITLE
CMake not found after installation on mac

### ISSUE THREAD

**Issue by dasanaei** [space-physics/igrf#10]
I am on Mac and after installation of igrf, the following error occured:
FileNotFoundError: CMake not available

This can be fixed by installing CMake using pip (pip install cmake). CMake should be added to the requirements/dependencies of igrc, as it is not automatically installed by either gcc or igrf.

**Comment by scivision** [comment]
Yes it's a matter of package author opinion. If someone has a version of CMake installed by one of many other means, I don't want to override that.
