### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by cnsnln** [space-physics/igrf#7]
* operating system (Windows, MacOS, Linux) Linux Ubuntu 20.04.2 LTS
* compiler & version (for compiled-source issues)  gfortran 
* Python version (for Python issues) python 3.8.5
I followed the instruction to install igrf using pip
python -m pip install igrf
I ran the example 
import igrf 
mag=igrf.igrf('2010-07-12',glat=65,glon=-148,alt_km=100)

I received an error with the message:
TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.

How do I fix the error?  

Chin Lin

**Comment by buaa-luzhi** [comment]
@cnsnln Did you solve it?

**Comment by cnsnln** [comment]
Not quite.  I ran the example code using jupyter-lab.   I received a syntax error,  SyntaxError: expression cannot contain assignment, perhaps you meant "==".   So I changed  to the following codes, and got some outputs.   However, the outputs disagree with those shown in the example.
glat = 65
glon = -148
alt_km=100
mag=igrf.igrf('2017-07-12',glat,glon,alt_km)
output
Data variables:
north (alt_km) float64 1.139e+04
east (alt_km) float64 3.589e+03
down (alt_km) float64 5.277e+04
total (alt_km) float64 5.411e+04
incl (alt_km) float64 77.25
decl (alt_km) float64 17.49

So, I think there are still some unresolved issues.

**Comment by buaa-luzhi** [comment]
thanks for your reply. Could you tell me how the code was modified. Thank again!

**Comment by buaa-luzhi** [comment]
I have solved the problem.  pip install xarray==0.15.0

**Comment by cnsnln** [comment]
@buaa-luzhi Do you get the same answers as the given example?    I pip install xarray==0.15.0.   It runs, but its outputs are not the same as the example.

**Comment by buaa-luzhi** [comment]
@cnsnln   is the same.

**Comment by dasanaei** [comment]
I had the same issue. xarray==0.15.0 solved it for me. I strongly suggest changing the requirements to specify the version of xarray during installation.

**Comment by scivision** [comment]
This was fixed in v13.0.1, thank you
